DROP SEQUENCE IF EXISTS media_seq;
DROP TABLE IF EXISTS genre_link CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS movie CASCADE;
DROP TABLE IF EXISTS tvshow CASCADE;

CREATE SEQUENCE media_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE genre_link
(
	genre_id    	BIGINT NOT NULL,
	media_type		VARCHAR (50) NOT NULL,
	media_id    	BIGINT NOT NULL
);

CREATE TABLE genre
(
	genre_id    	BIGINT NOT NULL,
	name		VARCHAR (50) NOT NULL
);

CREATE TABLE movie
(
	idMovie	BIGINT NOT NULL,
	c00			VARCHAR (100) NOT NULL,
	c07			VARCHAR (100) NOT NULL,   
	c08			VARCHAR (100) NOT NULL,
	c09			VARCHAR (100) NOT NULL,
	c14			VARCHAR (100) NOT NULL,
	c20			VARCHAR (100) NOT NULL,
	idSet	BIGINT NOT NULL
);

CREATE TABLE tvshow
(
	idShow	BIGINT NOT NULL,
	c00			VARCHAR (100) NOT NULL,
	c06			VARCHAR (100) NOT NULL,   
	c08			VARCHAR (100) NOT NULL,
	c11			VARCHAR (100) NOT NULL,
	c12			VARCHAR (100) NOT NULL
);