// Execute Tasks in SubModule: gradle MODULE:clean build
plugins {
    id("de.freese.gradle.conventions").version("$version_myJavaConventionPlugin").apply(false)
    id("io.spring.dependency-management").version("$version_springDependencyManagementPlugin").apply(false)
    id("org.openjfx.javafxplugin").version("$version_javafxPlugin").apply(false)
    id("org.springframework.boot").version("$version_springBoot").apply(false)
}

allprojects {
    apply(plugin: "base")
}

subprojects {
    apply(plugin: "de.freese.gradle.conventions")
    apply(plugin: "io.spring.dependency-management")

    dependencyManagement {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:" + property("version_springBoot"))
        }

        dependencies {
            dependency("com.github.kwhat:jnativehook:" + property("version_jnativehook"))

            dependencySet(group: "org.apache.xmlgraphics", version: "" + property("version_batik")) {
                entry("batik-codec")
                entry("batik-swing")
                entry("batik-transcoder")
            }

            dependency("net.jthink:jaudiotagger:" + property("version_jaudiotagger"))
            dependency("org.jfree:jfreechart:" + property("version_jfreechart"))
            dependency("tools.jackson.dataformat:jackson-dataformat-csv:" + dependencyManagement.importedProperties["jackson-bom.version"])
        }
    }

    pluginManager.withPlugin("java") {
        configurations.configureEach {
            exclude(group: "ch.qos.logback", module: "logback-classic")
        }
    }
}
