= syro

Music Player.

== Link

* https://github.com/JorenSix/TarsosTranscoder[TarsosTranscoder,window="_blank"]
* https://github.com/bramp/ffmpeg-cli-wrapper[ffmpeg-cli-wrapper,window="_blank"]
* https://github.com/processing/processing-sound[processing-sound,window="_blank"]
* http://samples.mplayerhq.hu[samples,window="_blank"]
* https://www.tek-tips.com/viewthread.cfm?qid=1358705[reading WAV,window="_blank"]

== Misc

* https://stackoverflow.com/questions/53997426/java-how-to-get-current-frequency-of-audio-input[frequency,window="_blank"]
* https://github.com/davidmoten/audio-recognition[audio-recognition,window="_blank"]

ffmpeg32 -i "02 Napali.m4a" -f ffmetadata metadata.txt

For example to show only audio streams, you can use the command:
ffprobe -show_streams -select_streams a INPUT ffprobe -show_format -show_streams -pretty "Black Wonderful Life.mp3" ffprobe -show_format -print_format json music.mp3 (flat, ini Writer)

How to play a byte array ?

[source,java]
----
public AudioInputStream getAudioInputStream(){
	final List<Byte> al = new ArrayList<>();
    final double frequency = 500D;
    final double rate = IntArray.rate;

	for (double time = 0; time <= rate*2; time++) {
		final short amplitude = (short) (8000D * Math.sin(2D * Math.PI * time / (44100D / frequency)));

        final byte[] bytePair = shortToBytes(amplitude);
        al.add(bytePair[0]);
        al.add(bytePair[1]);
	}

	final byte[] array = new byte[al.size()];

	for (int i = 0; i < array.length; i++) {
		array[i] = al.get(i);
	}

	return new AudioInputStream(in, new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 44100F, 16, 1, 4, 44100F, false), array.length);
}
----


// DFT
//
//Write the sound to an array of bytes
[source,java]
----
int nBytesRead = 0;
byte[] abData = new byte[EXTERNAL_BUFFER_SIZE];

while (nBytesRead != -1) {
	try {
		nBytesRead = audioInputStream.read(abData, 0, abData.length);
    }
    catch (IOException ex) {
		ex.printStackTrace();
    }

	if (nBytesRead >= 0) {
		int nBytesWritten = line.write(abData, 0, nBytesRead);
	}
}
----



//Calculate the sample rate
float sample_rate = audioFormat.getSampleRate(); +
System.out.println("sample rate = "+sample_rate);

//Calculate the length in seconds of the sample
float T = audioInputStream.getFrameLength() / audioFormat.getFrameRate(); +
System.out.println("T = "+T+ " (length of sampled sound in seconds)");

//Calculate the number of equidistant points in time
int n = (int) (T * sample_rate) / 2; +
System.out.println("n = "+n+" (number of equidistant points)");

//Calculate the time interval at each equidistant point
float h = (T / n); +
System.out.println("h = "+h+" (length of each time interval in seconds)");

//Determine the original Endian encoding format
boolean isBigEndian = audioFormat.isBigEndian();

//this array is the value of the signal at time i*h
int x[] = new int[n];

//convert each pair of byte values from the byte array to an Endian value
for (int i = 0; i < n*2; i+=2) {
int b1 = abData[i]; +
int b2 = abData[i + 1]; +
if (b1 < 0) b1 += 0x100; +
if (b2 < 0) b2 += 0x100;

	int value;

	//Store the data based on the original Endian encoding format
	if (!isBigEndian) value = (b1 << 8) + b2;
	else value = b1 + (b2 << 8);
	x[i/2] = value;
}

//do the DFT for each value of x sub j and store as f sub j
double f[] = new double[n/2]; +
for (int j = 0; j < n/2; j++) {
double firstSummation = 0; +
double secondSummation = 0;

	for (int k = 0; k < n; k++) {
     		double twoPInjk = ((2 * Math.PI) / n) * (j * k);
     		firstSummation +=  x[k] * Math.cos(twoPInjk);
     		secondSummation += x[k] * Math.sin(twoPInjk);
	}

    f[j] = Math.abs( Math.sqrt(Math.pow(firstSummation,2) + Math.pow(secondSummation,2)) );

	double amplitude = 2 * f[j]/n;
	double frequency = j * h / T * sample_rate;
	System.out.println("frequency = "+frequency+", amp = "+amplitude);
}
